[package]
name = "rust_ai_ml_adventure"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.17.0", features = [
  "dataset",
  "ndarray",
  "train",
  "vision",
] }
clap = { version = "4.5.38", features = ["cargo"] }
rand = "0.9.1"
